# Generated by Django 4.2 on 2023-04-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, unique=True)),
                ("password", models.CharField(max_length=256)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("chinese_id_card", "中国居民身份证"),
                            ("hkm_travel_permit", "港澳居民来往内地通行证"),
                            ("taiwan_travel_permit", "台湾居民来往大陆通行证"),
                            ("passport", "护照"),
                            ("foreign_permanent_resident_id", "外国人永久居留身份证"),
                            ("hmt_residence_permit", "港澳台居民居住证"),
                        ],
                        default="chinese_id_card",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("id_number", models.CharField(max_length=32)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("adult", "成人"),
                            ("child", "儿童"),
                            ("student", "学生"),
                            ("disability_military", "残军"),
                        ],
                        default="adult",
                        max_length=32,
                    ),
                ),
                (
                    "phone_region",
                    models.CharField(
                        choices=[
                            ("86", "+86"),
                            ("852", "+852"),
                            ("853", "+853"),
                            ("886", "+886"),
                        ],
                        default="86",
                        max_length=8,
                    ),
                ),
                ("phone_number", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
