# Generated by Django 4.2 on 2023-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passenger",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="passenger",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("CIC", "中国居民身份证"),
                    ("HTP", "港澳居民来往内地通行证"),
                    ("TTP", "台湾居民来往大陆通行证"),
                    ("PSP", "护照"),
                    ("FRI", "外国人永久居留身份证"),
                    ("HMT", "港澳台居民居住证"),
                ],
                default="chinese_id_card",
                max_length=3,
                verbose_name="证件类型",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="phone_region",
            field=models.CharField(
                choices=[
                    ("86", "+86"),
                    ("852", "+852"),
                    ("853", "+853"),
                    ("886", "+886"),
                ],
                default="86",
                max_length=3,
                verbose_name="地区",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="ticket_type",
            field=models.CharField(
                choices=[("ADU", "成人"), ("CHI", "儿童"), ("STU", "学生"), ("DOM", "残军")],
                default="adult",
                max_length=3,
                verbose_name="优惠(待)类型",
            ),
        ),
    ]
