# Generated by Django 4.2 on 2023-04-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-id"],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="邮箱地址"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.CharField(max_length=32, verbose_name="证件号码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("chinese_id_card", "中国居民身份证"),
                    ("hkm_travel_permit", "港澳居民来往内地通行证"),
                    ("taiwan_travel_permit", "台湾居民来往大陆通行证"),
                    ("passport", "护照"),
                    ("foreign_resident_id", "外国人永久居留身份证"),
                    ("hmt_residence_permit", "港澳台居民居住证"),
                ],
                default="chinese_id_card",
                max_length=32,
                verbose_name="证件类型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=128, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=32, verbose_name="手机号码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_region",
            field=models.CharField(
                choices=[
                    ("86", "+86"),
                    ("852", "+852"),
                    ("853", "+853"),
                    ("886", "+886"),
                ],
                default="86",
                max_length=8,
                verbose_name="地区",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("adult", "成人"),
                    ("child", "儿童"),
                    ("student", "学生"),
                    ("DM", "残军"),
                ],
                default="adult",
                max_length=16,
                verbose_name="优惠(待)类型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=128, unique=True, verbose_name="用户名"),
        ),
    ]
