# Generated by Django 4.2 on 2023-05-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="seat_id",
            new_name="seat",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="train_id",
            new_name="train",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="seat",
            old_name="train_id",
            new_name="train",
        ),
        migrations.RenameField(
            model_name="stop",
            old_name="station_id",
            new_name="station",
        ),
        migrations.RenameField(
            model_name="stop",
            old_name="train_id",
            new_name="train",
        ),
    ]
